// Re-export shared, types-only protocol contracts for webview usage
export type {
    Model,
    BaseWorkflowMessage,
    NodeExecutionPayload,
    NodeSavedState,
    WorkflowStateDTO,
    WorkflowPayloadDTO,
    WorkflowNodeDTO,
    EdgeDTO,
    SubflowPortDTO,
    SubflowDefinitionDTO,
    WorkflowToExtension,
    ExtensionToWorkflow,
    // Individual event types for discriminated union narrowing
    WorkflowLoadedEvent,
    WorkflowSavedEvent,
    WorkflowSaveFailedEvent,
    NodeExecutionStatusEvent,
    TokenCountEvent,
    NodeAssistantContentEvent,
    ModelsLoadedEvent,
    ProvideCustomModelsEvent,
    ExecutionCompletedEvent,
    ExecutionPausedEvent,
    SubflowCopiedEvent,
    ProvideSubflowEvent,
    ProvideSubflowsEvent,
} from '../../Core/Contracts/Protocol'
